# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='date',
        ),
        migrations.RemoveField(
            model_name='call',
            name='type',
        ),
        migrations.RemoveField(
            model_name='call',
            name='user_id',
        ),
    ]
