# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0008_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='categ',
            field=models.CharField(default='ggg', max_length=46),
        ),
        migrations.AlterField(
            model_name='call',
            name='type',
            field=models.BooleanField(choices=[(True, 'Предложение'), (False, 'Поиск')], default=True),
        ),
    ]
