# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0010_remove_call_categ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='date',
        ),
    ]
