# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sp', '0012_auto_20170330_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(choices=[(True, 'Предложение'), (False, 'Поиск')], default=True, verbose_name='Тип')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('card', models.ImageField(blank=True, upload_to='sp/cards', verbose_name='Изображение')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Список тегов через запятую.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя')),
            ],
        ),
    ]
