# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0013_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
    ]
