# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0015_todelete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todelete',
        ),
    ]
