# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0016_delete_todelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='card',
            field=models.ImageField(blank=True, max_length=30, upload_to='sp/cards', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='call',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Список тегов через запятую', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
