# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0017_auto_20170405_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='card',
            field=models.ImageField(blank=True, upload_to='sp/cards', verbose_name='Изображение'),
        ),
    ]
