# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sp', '0018_auto_20170405_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('education', models.CharField(max_length=30, verbose_name='Образование')),
                ('gender', models.CharField(choices=[('Не указано', 'Не указано'), ('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=30, verbose_name='Пол')),
                ('offers', models.TextField(verbose_name='Предложения')),
                ('search', models.TextField(verbose_name='Поиск')),
                ('e_mail', models.CharField(max_length=30, verbose_name='e-mail')),
                ('vk_com', models.CharField(max_length=30, verbose_name='vk.com')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id пользователя')),
            ],
        ),
    ]
