# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0022_auto_20170420_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vk_com',
        ),
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.TextField(blank=True, verbose_name='Другие контакты'),
        ),
    ]
